### ISSUE TITLE
Automatically parse request object

### ISSUE THREAD

**Issue by inigomarquinez** [kevinccbsg/config-req#4]
Be able to send the `request` object so `body` and `urlParams` can be directly parsed instead of explicitly having to set them.

**Comment by kevinccbsg** [comment]
This is in working progress status. In this branch https://github.com/kevinccbsg/config-req/tree/req-options 👍 

It needs more documentation and better testing.

**Comment by inigomarquinez** [comment]
That's great!!! Will it be merged to master or will it live as an independent branch?

**Comment by kevinccbsg** [comment]
It will be merged with the master branch.

**Comment by kevinccbsg** [comment]
This was merged @inigomarquinez. I'd recommend checking this https://github.com/kevinccbsg/config-req#use-with-req-complete-object to use in your projects until V2 will be released.
